junyiacademy/junyiexercise

- utils/answer-types.js
There would be some mistakes for unit conversion.
So remove commas function.
> [rm commas function]

- exercises/attributs_of_shapes.html
均一修改_141231 依附件「attributs of shapes.docx」調整
> sunrise-fixbug-attributs_of_shapes-issue

- exercises/sort-groups-by-count_1.html
均一修改_141231 依附件「attributs of shapes.docx」調整調整未作答時顯示出錯
> sunrise-fixbug-sort-groups-by-count_1-issue

- exercises/naming_shapes_2.html
均一修改_141231依附件「naming shapes 2.docx」調整
> sunrise-fixbug-naming_shapes_2-issue

- exercises/count_number_to_50.html
> Ensure chg3 runs only one time

- exercises/repeated_addition.html
modify content about case3 in repeated_addition.html
case3的羅賓case，修改為只會寫3篇日記。
> [Modify exercise]

- exercises/adding_decimals_0.5_new.html
> adding decimals 0.5 new

- exercises/multiplication_with_carrying.html
> made by sunrise 1224

- exercises/adding_decimals_2_new.html
> add decimals 2 new

- exercises/comparing_decimal_place_value.html
> comparing decimal place value

- exercises/decomposing_fractions.html
> sunrise-fixbug-decomposing_fractions-issue

- exercises/comparing_lengths.html
> sunrise-fixbug-comparing_lengths-issue

- exercises/number_line_0.5_new.html
依據均一修改_20150105郵件中，參考此number_line_0.5題形式，另外製作所有case不要出現負數的「不同檔名」新題目
> sunrise-commit-number_line_0.5_new

- exercises/number_line_0.7_new.html
依據均一修改_20150105郵件中參考此number_line_0.7題形式，另外製作所有case不要出現負數的「不同檔名」新題目
> sunrise-commit-number_line_0.7_new

- exercises/recognize_decimal_percentile_position.html
依據均一修改_20150108郵件中請讓定位版限制一格只能輸入一個數字，並讓答案有顏色
> sunrise-fixbug-recognize_decimal_percentile_position-issue

- exercises/understand_length_unit.html
依據均一修改_150108郵件中，case4 請將人名變數改為「工廠」
「收集」改為「儲存」
物品變數中的「彈珠」改為「電線」，石頭則可以保留
> sunrise-fixbug-understand_length_unit-issue

- exercises/complex_number_polar_form_intuition_new.html
> sunrise-fixbug-complex_number_polar_form_intuition_new.html-issue

- exercises/understand_length_unit.html
Reverts junyiacademy/junyiexercise#78
> Revert "sunrise-fixbug-understand_length_unit-issue"

- exercises/skip_counting_by_10s.html
> Skip counting by 10s

- exercises/length_word_problem.html
> Length word problem

- exercises/comparing_decimals_2.html
> comparing decimals 2

- exercises/comparing_decimals_1.html
> comparing_decimals_1

- exercises/interpreting_absolute_value.html
> Interpreting absolute value

- exercises/ordering_decimals_new.html
> ordering decimals new

- exercises/solving_problems_with_line_plots_1.html
均一修改_141231 依附件「小黑規格review2.docx」調整
> sunrise-ficbug-solving_problems_with_line_plots_1-issue

- exercises/visualizing_equivalent_fraction.html
> sunrise-fixbug-visualizing_equivalent_fraction-issue

- exercises/using_fractions_to_divide_pizzas_pies_and_cakes.html
依照均一修改-141231中fix [置換翻譯如附件「Using fractions to divide pizzas, pies, and cakes_fix.docx
> sunrise-fixbugusing_fractions_to_divide_pizzas_pies_and_cakes issue

- exercises/application_of_GCD_and_LCM_1.html
該檔案製作根據2014-12-31日中最大公因數與最小公倍數應用題6-n-02（博幼）規格製作。
> sunrise-commit-application_of_GCD_and_LCM_1

- exercises/quadrilateral_types.html
依據均一修改20150105郵件中答案不一致，並且給答案加上顏色
> sunrise-fixbug-quadrilateral_types-issue

- exercises/understand_coins.html
依據均一修改20150105郵件中每一case限制錢的數量不要超過100
> sunrise-fixbug-understand_coins-issue

- exercises/addition_two_numbers.html
> sunrise-fixbug-addition_two_numbers

- exercises/ratio_and_the_ratio_of.html
ratio_and_the_ratio_of
case1:floating issue；占》佔
case2:
請接受比值是小數的答案；題目中</code>改為<code>
case3:
比值改為以分數呈現，並一樣接受小數的答案；重量》體重；提示刪除多餘的</var>標籤，將×改為\times
case4:去回程的時速請介於40-70公里之間，比較合理也比較好計算
case7:請接受比值是小數的答案
> Sunrise fixbug ratio and the ratio of

- exercises/meaning_of_equal_sign.html
> sunrise_fixbug-meaning_of_equal_sign-issue

- exercises/measuring_lengths_with_different_units.html
長方形的寬度要有變化，厘米->公分，釐米->公分，绿线->綠線
> sunrise-fixbug-measuring_lengths_with_different_units

- exercises/decimals_on_the_number_line_2_new.html
> Decimals on the number line 2 new

- exercises/constructing_and_interpreting_absolute_value.html
山高 用公尺來當單位 ，數字約分；軍--》睿 兵-》野 case1  是-》在，香蕉滑到-》滑倒
解答-》作答   距離-》差距
> sunrise-fixbug-constructing_and_interpreting_absolute_value

- exercises/multiplying_and_dividing_negative_numbers_new.html
如果式子中有0時，提示改為0乘以任何數結果都會是0。0除以任何數結果都會是0。
> sunrise-fixbug-multiplying_and_dividing_negative_numbers_new-issue

- exercises/composing_shapes.html
修改在composing是2的case底下，set_graphies = 5和set_graphies = 1畫出來的圖是一樣的，造成答案錯誤。無法驗證的錯誤
> sunrise-fixbug-composing_shapes-issue

- exercises/volume_of_rectangular_boxes_2.html
均一修改_150204_急件，邊長與對應的邊長值加上顏色，以免使用者作答時邊長與值對應出錯的問題。
> sunrise-fixbug-volume_of_rectangular_boxes_2

- khan-exercise.js
- utils/mean-and-median.js
@rogertigerchen EJ大大，翻譯完囉！麻煩你了
> Translation mean and mediam

- exercises/scale_see_compare_see.html
> sunrise-commit-scale_see_compare_see

- exercises/short_divide_GCF_and_LCM.html
均一習題html規格書：6-n-02 最大公因數與最小公倍數應用題（短除法)
> Sunrise commit short divide gcf and lcm

- exercises/radius_angle_by_percentage.html
依據20150204新習題規格郵件中 均一習題html規格書：6-d-01運用百分率算出圓心角.docx製作
> sunrise-commit-radius_angle_by_percentage

- exercises/compound_numbers_world_problems.html
依據20150126.均一習題html規格書：4-n-14能以複名數解決量的文字應用問題.docx製作
> sunrise-commit-compound_numbers_world_problems

- exercises/difference_between_solid_and_plane_graphics.html
依據均一習題html規格書：5-s-06 區別立體圖形與平面圖形
> sunrise-commit-difference_between_solid_and_plane_graphics

- exercises/cube_rectangular_and_regular_tetrahedron.html
依據均一html習題規格書：5-s-06 正方體、長方體與正四面體
> sunrise-commit-cube_rectangular_and_regular_tetrahedron

- exercises/meters_and_centimeters_conversion.html
依據20150126均一習題html規格書：3-n-14公尺與公分的換算.docx製作
> sunrise-commit-meters_and_centimeters_conversion

- exercises/understand_percentage.html
依據20150204郵件中均一習題html規格書：5-n-12 認識百分率 製作
> sunrise-commit-understand_percentage

- exercises/tenfold_and_hundred_fold.html
依據20150129郵件中均一html習題規格書：3-n-04 整十倍與整百倍 製作
> sunrise-commit-tenfold_and_hundred_fold

- khan-exercise.js
在練習題、答對了請做下一題的地方
ipad有時候還是會卡住，解決的方法是
把時間限制拿掉
> Save bug stucking at "答對了請做下一題"

- khan-exercise.js
Ipad don't have focus function...
> Separate the focus function from ipad

- exercises/multiplying_fractions_and_whole_numbers_word_problems.html
> sunrise-fixbug-multiplying_fractions_and_whole_numbers_word_problems

- exercises/fraction_and_per_swap_divide.html
依據2015-02-04均一習題html規格書：5-n-12 分數與百分率互換（可整除）.docx規格製作
> sunrise-commit-fraction_and_per_swap_divide

- exercises/fractions_and_percentage_of_exchange.html
依據2015-02-04均一習題html規格書：5-n-12 分數與百分率互換（不可整除）.docx規格製作
> sunrise-commit-fractions_and_percentage_of_exchange

- exercises/g_and_kg_word_problems.html
依據2015-01-12均一習題html規格書：3-n-16 公克與公斤的文字應用題.docx規格製作
> sunrise-commit-g_and_kg_word_problems

- exercises/understand_coins.html
@rogertigerchen EJ大大，第一個commit是我把understand_coins複製到另外一個新的understand_coins，原因是understand_coins是從蘇州回來的html，他們用的編輯器可能跟我們不一樣，所以我們只要做一點點的修改時，會有很大的跑版(在編輯器的跑版，不是瀏覽器看到的跑版)，所以我新建一個一模一樣的understand_coins，解決這個問題，第二個commit才是我做的修改。
> Understand coins fixbug

- exercises/cube_volume_calculation.html
依據郵件20150210新習題規格 均一習題html規格書：5-n-20、5-s-07正方體體積的計算.docx文檔製作
> sunrise-commit-cube_volume_calculation

- exercises/cc_and_cubic_meter_conversion.html
依據郵件20150210新習題規格  均一習題html規格書：5-n-19 立方公分與立方公尺換算-2.docx 製作
> sunrise-commit-cc_and_cubic_meter_conversion

- exercises/telling_time.html
- exercises/telling_time_0.5.html
- utils/time.js
時針變短加粗變色。分針變色，所以修改time,js
修改telling_time和telling_time_0.5讓作答格在同一行，提示答案加上顏色
> sunrise-fixbug-telling_time-issue

- exercises/common_form_for_life.html
> edit answer number

- exercises/fractions_cut_and_copy.html
- exercises/fractions_cut_and_copy_1.html
- exercises/fractions_cut_and_copy_2.html
- utils/slice-clone.js
fractions_cut_and_copy解決超版，修改slice-clone.js文件，一併修改了fractions_cut_and_copy_1和fractions_cut_and_copy_2
fractions_cut_and_copy和fractions_cut_and_copy_1分母改為 2~6, 分子改為 2~9 ,
> sunrise-fixbug-fractions_cut_and_copy _1 _2

- exercises/division_word_problems_2.html
> 作答區設計為2個格子，答案驗證，提示及答案的上色

- exercises/multiplication_3.html
> multiplication_3和4合併在multiplication_3中

- exercises/division_1.5.html
> 修改所有2位數為3位數

- exercises/count_numbers.html
1.刪除沒用的js方法
2.修改未作答驗證錯誤
3.使原來固定的答案位置改為隨機
> 修改在未作答前驗證答案為錯誤的問題

- exercises/congruent_triangles_1.html
1.上下分為兩個畫圖區域顯示兩個三角形，解決部分重疊問題
2.兩個三角形相對大小不會差太多，使角度顯示清晰
3.修改答案顏色為hint_pink
> 使兩個三角形的比例在1：（0.7,1.2）之間，讓三角形上的角度顯示更清晰

- exercises/multiplication_1.5.html
> sunrise-fixbug-multiplication_1.5

- exercises/rates_and_ratios.html
> sunrise-fixbug-rates_and_ratios

- exercises/equal_parts_of_circles_and_rectangles.html
1.調整不明顯的答案，讓答案的差別更大
2.正方形長方形等分畫圖更精確（從上至下分成4份的答案）
3.避免出現重複的圖形
> sunrise-fixbug-equal_parts_of_circles_and_rectangles

- exercises/side_length_cube_and_relationship_with_volume_cuboid.html
依據20150210新習題規格中export.docx文檔，習題名稱正方體及長方體邊長與體積的關係，製作
> sunrise-commit-side_length_cube_and_relationship_with_volume_cuboid

- exercises/cuboid_volume_calculation.html
依據郵件20150210新習題規格 均一習題html規格書：5-n-20、5-s-07長方體體積的計算.docx 製作
> sunrise-commit-cuboid_volume_calculation

- exercises/age_word_problems.html
- utils/math-format.js
> 修改題目顯示及當年份大於20年以上正確顯示中文讀法

- exercises/simple_calculation_of_composite_volume.html
依據均一習題html規格書：5-n-20、5-s-07簡單複合形體體積計算.docx製作
> sunrise-commit-simple_calculation_of_composite_volume

- exercises/fraction_multiplication_as_scaling.html
> sunrise-fixbug-fraction_multiplication_as_scaling

- exercises/multiplying_fractions_by_fractions_word_problems.html
case3:題目改為一條繩子長6 6/7公尺，5/6條繩子長幾公尺？
case4 名字顯示完整；
case6 牙膏改成洗衣精、洗碗精、沐浴乳。盎司改成公升
case8條》胎；case10 个》個；case9畫圖有誤修改
> sunrise-fixbug-multiplying_fractions_by_fractions_word_problems

- exercises/summand_or_unknown_addend_calculation_problems.html
根據2-16日新習題規格郵件中 均一習題html規格書：5-a-04 被加數或加數未知的計算題.docx製作
> sunrise-commit-summand_or_unknown_addend_calculation_problems

- exercises/multiplicand_or_unknown_multiplier_calculation_problems.html
根據2-16日新習題規格郵件中 均一html習題：5-a-04 被乘數或乘數未知的計算題.docx製作
> sunrise-commit-multiplicand_or_unknown_multiplier_calculation_problems

- exercises/minuend_or_subtrahend_unknown_calculation_problems.html
根據2-16日新習題規格郵件中 均一習題html規格書：5-a-04被減數或減數未知的計算題.docx製作
> sunrise-commit-minuend_or_subtrahend_unknown_calculation_problems

- exercises/dividend_or_unknown_divisor_calculation_problems.html
根據2-16日新習題規格郵件中 均一html習題規格書：5-a-04 被除數或除數未知的計算題.docx製作
> sunrise-commit-dividend_or_unknown_divisor_calculation_problems

- exercises/metric_weight_unit_selection.html
case elevator正確答案驗證，所有case答案上色
> sunrise-fixbug-metric_weight_unit_selection

- exercises/triangles_congruent_nature_sss.html
case4線段 CS = 線段 CS 應改為 線段 CS = 線段 CH，答案上色
> sunrise-fixbug-triangles_congruent_nature_SSS

- exercises/morning_afternoon_night.html
> sunrise-fixbug-morning_afternoon_night

- css/khan-exercise.css
- exercises/comparison_between_numbers_within_ten_0.5.html
- exercises/count_one_by_one_1.html
above-scratchpad 這個class加在 khan-exercise.css裡面，在開啟計算紙時，作答區加上這個class就不會被遮住了！
> Add above scratchpad

- utils/answer-types.js
The mathjax render is done in a queue which we don't know
whether it's done or not. Remove mathjax things so we are
sure what we got.
> Remove mathjax before getting the answer index

- exercises/conversion_of_volume_and_capacity.html
依據20150305新習題規格郵件中 均一習題html規格書：5-n-21 容積與容量的換算1_2.docx 製作
> Sunrise commit conversion of volume and capacity

- exercises/volume_calculation_liquid_solid_basic.html
依據3.10郵件中 均一習題html規格書：5-n-21 液體與固體的體積計算-基礎.docx製作
> sunrise-commit-volume_calculation_liquid_solid_basic

- exercises/understand_coins.html
> sunrise-fixbug-understand_coins

- exercises/vertical_and_parallel.html
> sunrise-fixbug-vertical_and_parallel

- exercises/cuboid_volume_calculation.html
> sunrise-fixbug-cuboid_volume_calculation

- exercises/creating_bar_charts_1.html
> sunrise-fixbug-creating_bar_charts_1

- exercises/judging_axis_of_symmetry.html
case3
1.ABCB 》ABCD
2.EF沒》AC
答案上色
> sunrise-fixbug-judging_axis_of_symmetry

- exercises/division_2.9.html
- exercises/division_3.html
題目與可接受格式中「請輸入答案為"5 R 3"」的敘述去除，
作答區改成2格，一格驗證商的答案、一格驗證餘數的答案。（可接受格式都改成整數）
修改相同問題的division_3
> sunrise-fixbug-division_2.9

- exercises/area_square_km_units_word_problems.html
根據 20150317新習題規格郵件中 均一習題html規格書：5-n-17公畝、公頃、平方公里單位的文字應用題.docx 製作
> sunrise-commit-area_squre_km_units_word_problems

- exercises/t_and_kg_exchange.html
根據 20150317新習題規格郵件中 均一習題html規格書：5-n-16 公噸與公斤的換算.docx 製作
> sunrise-commit-t_and_kg_exchange

- exercises/advanced_fraction.html
> sunrise-fixbug-advanced_fraction

- exercises/area_calculation_advanced.html
根據3、23日郵件 均一習題html規格書：5-n-20、5-s-07 表面積的計算-進階.docx 製作
> sunrise-commit-area_calculation_advanced

- exercises/log_table.html
依據習題規格_150119郵件中 均一習題html規格書：指對數 查對數表(1~10).pdf 製作
> sunrise-commit-log_table

- exercises/volume_calculation_advanced.html
根據20150305新習題規格郵件中 均一習題html規格書：5-n-21 容積的計算-進階.docx 製作
> sunrise-commit-volume_calculation_advanced

- exercises/circle_arc_chord_bow_fan.html
根據03-13 郵件中 均一習題html規格書：8-s-20 圓的相關名詞：弦、弓形、扇形-2.docx 製作。
> sunrise-commit-circle_arc_chord_bow_fan

- exercises/dividing_fractions_negative.html
將原有的檔案切分成2個，1個有負數，1個沒有負數，
dividing_fractions沒有負數，答案加顏色。
dividing_fractions_negative有負數
> sunrise-dividing_fractions&&negative

- exercises/ordering_negative_numbers.html
增加 使用者排列的順序「完全相反」，出現灰色字提示
解決超版以及未作答提示回答錯誤，
答案顏色改為粉色。
> sunrise-fixbug-ordering_negative_numbers

- exercises/relation_between_point_and_line.html
依據 3-26郵件中 均一習題html規格書：點與直線關係 .pdf 製作
> sunrise-commit-relation_between_point_and_line

- exercises/angular_bisector.html
依據3-26郵件中  均一習題html規格書：8-s-06 線對稱的意義 - 角平分線的概念.pdf 製作
> sunrise-commit-angular_bisector

- exercises/the_fundamental_theorem_of_arithmetic.html
> sunrise-fixbug-the_fundamental_theorem_of_arithmetic

- exercises/vertical_judgment.html
依據3-26 郵件中 均一習題html規格書：8-s-06 線對稱的意義 - 垂直與點到直線最短距離.pdf製作
> sunrise-commit-vertical_judgment

- exercises/multiplicand_or_unknown_multiplier_calculation_problems.html
修改 提示的圖示需 很多段直線接在一起，但是中間沒有間隔的感覺，學生看不出來到底接到了幾段問題
在線與線之間加入點以作為區別
> sunrise-fixbug-multiplicand_or_unknown_multiplier_calculation_problems

- khan-exercise.js
加上判斷是否在預覽頁面，若是，Exercises就是undefined，即可避掉錯誤
> make the preview page won't get error when submit answer and click hint

- exercises/calculate_the_length_of_the_cuboid.html
3-30郵件中 均一習題html規格書：5-n-20、5-s-07長方體邊長的計算.docx
> sunrise-commit-calculate_the_length_of_the_cuboid

- exercises/perpendicular_bisector.html
3-26郵件中 均一習題html規格書：垂直平分線的概念.pdf
> sunrise-commit-perpendicular_bisector

- exercises/arch_perimeter_and_area.html
3-24郵件中 均一習題html規格書：8-s-21 弧長的公式及扇形面積 - 弓形的面積.docx
> sunrise-commit-arch_perimeter_and_area

- exercises/triangle_interior_exterior_angle_sum.html
20150415郵件 均一習題html規格書：8-s-03 凸多邊形內外角和 - 三角形的內角和與外角和-2.pdf
> sunrise-commit-triangle_interior_exterior_angle_sum

- exercises/the_cube_surface_area.html
20150323郵件中 均一習題html規格書：5-n-20、5-s-07正方體的表面積計算.docx
> sunrise-commit-the_cube_surface_area

- exercises/angular_bisector_meaning.html
20150407郵件中 均一習題html規格書：8-s-06 線對稱的意義 - 角平分線與中垂線.pdf
> sunrise-commit-angular_bisector_meaning

- exercises/calculate_the_length_of_the_cube.html
20150330 郵件中 均一習題html規格書：5-n-20、5-s-07 正方體邊長的計算.docx
> sunrise-commit-calculate_the_length_of_the_cube

- exercises/characteristics_of_cuboid.html
20150330 郵件中 均一習題html規格書：5-n-20、5-s-07 長方體的特性.docx
> sunrise-commit-characteristics_of_cuboid

- exercises/triangle_interior_exterior_angle_sum_comprehensive.html
2015-4-15郵件中 均一習題html規格書：8-s-03 凸多邊形內外角和 - 三角形的內角和與外角和綜合題型.pdf  製作
> sunrise-commit-triangle_interior_exterior_angle_sum_comprehensive

- exercises/characteristics_of_the_symmetry_axis.html
2015-4-15郵件中 均一習題html規格書：對稱軸的特性.pdf  製作
> sunrise-commit-characteristics_of_the_symmetry_axis

- exercises/absolute_values_meaning.html
解決超版，以及case2中答案的數字應不包含與題目相等的數字（如正負17），>,<改為&gt; &lt;
> sunrise-fixbug-absolute_values_meaning

- exercises/parallel_lines_judgment_basic.html
2015-4-27 郵件中 均一 html 規格書：平行線的判別方法-2.docx製作
> sunrise-commit-parallel_lines_judgment_basic

- exercises/hub_theorem_and_inverse_theorem.html
2015-4-27 郵件 均一習題html規格書：8-s-16 三角形的邊角關係 - 樞紐定理與逆樞紐定理.pdf製作
> sunrise-commit-hub_theorem_and_inverse_theorem

- exercises/corner_of_the_triangle_relationship.html
2015-4-27 郵件中 均一習題html規格書：8-s-16 三角形的邊角關係 - 三角形的邊角關係.pdf製作
> sunrise-commit-corner_of_the_triangle_relationship

- interface.js
- because if user click the button too fast, the server will get 'problemNumber out of order'
> set timeout to make the skip button show up later

- exercises/area_unit_cm_square.html
- exercises/hub_theorem_and_inverse_theorem.html
- exercises/multiplying_mixed_numbers_1.html
> Sunrise fixbug multiplying mixed numbers 1

- exercises/area_unit_cm_square.html
> 面積單位平方公分實測計算（case2）

- exercises/area_unit_cm_square.html
- exercises/hub_theorem_and_inverse_theorem.html
> Sunrise fixbug hub theorem and inverse theorem

- exercises/parallel_quadrilateral_nature.html
> 平行四邊形的性質 2015/5/15

- exercises/parallel_quadrilateral_differentiate.html
> 平行四邊形的判別 2015-05-15

- exercises/parallel_quadrilateral_meaning.html
> 平行四邊形的意義 2015-05-15

- exercises/ratio_money.html
答案區域及最後一行提示答案處，時改為小時，分改為分鐘
修改提示答案的顏色為pink
> 修改格式提示以及答案驗證,local端OK

- exercises/notation_calculation_type.html
> Sunrise fixbug notation calculation type

- exercises/parallel_quadrilateral_area.html
- exercises/parallel_quadrilateral_nature.html
> Sunrise commit parallel quadrilateral area

- exercises/inequality_signs_significance.html
> 不等式符號的意義 20150608

- exercises/ratio_revision.html
> 複習比大小 20150608

- exercises/symmetrical_line_graphics.html
根據 2015-4-15郵件中 均一習題html規格書：線對稱圖形作圖.pdf 製作
> sunrise-commit-symmetrical_line_graphics

- exercises/number_of_necessary_ratings.html
根據2015-4-15郵件中 均一 html 規格書：平分所需的作圖次數.pdf 製作
> sunrise-commit-number_of_necessary_ratings

- exercises/sort-groups-by-count_1.html
> case3, 5改為1個子題

- exercises/understanding_comparing_angle.html
case1改成比較好點、感應區域比較寬的形式，id=s的部分，但是好像比較有多處不同。。不知道是什麼原因。還希望您check的時候看一看。
> case1改成比較好點、感應區域比較寬的形式

- exercises/volume_of_rectangular_boxes_3.html
> 旋轉圖形題目改製為靜態圖形

- exercises/count_number_to_100.html
> 解決case2會有2個空格出現問題

- exercises/simple_calculation_of_composite_volume.html
> 旋轉圖形題目以其他方式改製,看不到的地方用虛線

- exercises/parallel_lines_judgment_basic.html
按照安強的要求 圖形上兩條線的角度縮小，避免一眼看出來是否平行，但有沒有平行看角度的數字才知道
> 圖形上角度縮小，避免一眼看出來是否平行

- exercises/surface_area_of_rectangular_boxes.html
> 動態圖形改制為靜態圖形

- exercises/the_cube_surface_area.html
> 將動態圖形改制為靜態圖形

- exercises/volume_calculation_liquid_solid_advance.html
3-10 均一習題html規格書：5-n-21 液體與固體的體積計算-進階-2
> sunrise-commit-volume_calculation_liquid_solid_advance

- exercises/corner_of_the_triangle_relationship.html
依据5月15日安强邮件中 把case1,2,4改成五选一的单选题
> sunrise-corner_of_the_triangle_relationship-fixbug

- exercises/isosceles_trapezoid_characteristics.html
> sunrise-isosceles_trapezoid_characteristics-commit

- exercises/herons_formula.html
海隆=》海龍
答案上色
另外修改div.vars中初始化，否則報error，雖然不影響使用
> Sunrise fixbug herons formula

- exercises/triangle_angles_1.html
> 調整圖中角度的提示，答案上色

- exercises/basic_concept_of_congruent_triangles.html
> sunrise-fixbug-basic_concept_of_congruent_triangles

- exercises/hub_theorem_and_inverse_theorem.html
> sunrise-fixbug-hub_theorem_and_inverse_theorem

- exercises/multiplication_formula_1.html
> sunrise-fixbug-multiplication_formula_1

- exercises/understanding_square_rectangular.html
> sunrise-fixbug-understanding_square_rectangular

- exercises/pyramidal_prism.html
答案驗證增加 data-type="text" local端OK，麻煩測試
> sunrise-fixbug-pyramidal_prism

- exercises/circumferential_angle.html
> sunrise-fixbug-circumferential_angle

- exercises/volume_box_cover.html
> sunrise-fixbug-volume_box_cover

- exercises/equation_of_a_hyperbola.html
> sunrise-fixbug-equation_of_a_hyperbola

- exercises/understanding_decimals_place_value.html
and -》 和
去掉注釋，local端有注釋時 IE8有問題
> sunrise-fixbug-understanding_decimals_place_value

- exercises/adding_and_subtracting_centimeter_and_millimeter.html
> sunrise-fixbug-adding_and_subtracting_centimeter_and_millimeter

- exercises/count_number_to_100.html
> sunrise-fixbug-count_number_to_100

- exercises/inequalities_on_a_number_line_2.html
20150614 均一習題 html 規格書：數線上的不等式2 inequalities_on_a_number_line_2
> sunrise-commit-inequalities_on_a_number_line_2

- khan-exercise.js
- utils/answer-types.js
> Fraction input

- exercises/multiplying_decimal_integer.html
- utils/graphie-helpers-arithmetic.js
1.修改答案驗證統一提示，麻煩檢查提交後答案驗證功能是否正常
2.修改graphie-helpers-arithmetic.js中Multiplier方法的下邊界
> sunrise-fixbug-multiplying_decimal_integer

- exercises/points_lines_and_planes.html
- utils/answer-types.js
1.去掉注釋
2.答案標為hint_pink
3.英文提示改為中文
> sunrise-fixbug-points_lines_and_planes

- exercises/scientific_notation_intuition.html
> sunrise-fixbug-scientific_notation_intuition

- exercises/percentage_word_problems_1.html
> sunrise-fixbug-percentage_word_problems_1

- exercises/sequences_word_problems.html
> sunrise-fixbug-sequences_word_problems

- exercises/least_common_multiple.html
> sunrise-fixbug-least_common_multiple

- exercises/proportional_life_problems.html
修改case=speed答案驗證方式，增加data-type="text"，local端OK
> sunrise-fixbug-proportional_life_problems

- exercises/subtracting_fractions.html
> sunrise-fixbug-subtracting_fractions

- exercises/volume_box_nocover.html
> sunrise-fixbug-volume_box_nocover

- exercises/negative_number_word_problems.html
> sunrise-fixbug-negative_number_word_problems

- exercises/triangle_interior_exterior_angle_sum_comprehensive.html
> sunrise-fixbug-triangle_interior_exterior_angle_sum_comprehensive

- exercises/unit_conversion_rate.html
> sunrise-fixbug-unit_conversion_rate

- exercises/understanding_comparing_angle.html
https://trello.com/c/5PyM8N84/39-case1
改變角的可選區域，由於該題選擇點選角度是在一整張大圖上，無法做到隨機，可以考慮把圖片切割，每題出現幾張圖片給學生點選，如果要做成這種效果的話後續再進行修改
> sunrise-fixbug-understanding_comparing_angle

- exercises/adding_and_subtracting_negative_numbers.html
https://trello.com/c/uJia743X/88--
調整畫圖上下間隔
> sunrise-fixbug-adding_and_subtracting_negative_numbers

- exercises/order_of_operations.html
https://trello.com/c/dfDHuBKO/87--
去除帶分數的題目
> sunrise-fixbug-order_of_operations

- exercises/percentage_word_problems_2.html
> sunrise-fixbug-percentage_word_problems_2

- exercises/congruent_triangles_2.html
https://trello.com/c/6Jn2KjNY/35-2-opposite
調整數字，避免重疊
> Sunrise fixbug congruent triangles 2

- exercises/graphs_of_sine_and_cosine.html
https://trello.com/c/lLVemhtT/84-sin-cos
修改sine=》sin，cosine=》cos
> sunrise-fixbug-graphs_of_sine_and_cosine

- exercises/radius_angle.html
> Sunrise fixbug radius angle

- exercises/trigonometry_0.5.html
修改提示
https://trello.com/c/rIh2ST0b/77-0-5
> sunrise-fixbug-trigonometry_0.5

- exercises/trigonometry_1.html
修改提示
https://trello.com/c/VCjEeUt6/78-1
> sunrise-fixbug-trigonometry_1

- exercises/pythagorean_theorem_2.html
線條上方加上橫線
https://trello.com/c/RaECsrnK/76-2
> sunrise-fixbug-pythagorean_theorem_2

- exercises/systems_of_equations_word_problems.html
https://trello.com/c/FlB3aYsw/96-substitution-y
去除多餘英文
> sunrise-fixbug-systems_of_equations_word_problems

- exercises/discount_tax_and_tip_word_problems.html
https://trello.com/c/Dc6qfR4j/94--
提示修改
> Sunrise fixbug discount tax and tip word problems

- exercises/multiplication_formula_sub.html
https://trello.com/c/4pQcmhFR/91--
刪除case，修改數值精度問題
> sunrise-fixbug-multiplication_formula_sub

- exercises/degrees_to_radians.html
https://trello.com/c/823ERUpp/83--
英文改弧度
> Sunrise fixbug radians and degrees

- exercises/radius_diameter_and_circumference.html
> sunrise-fixbug-radius_diameter_and_circumference

- exercises/trigonometry_1.5.html
https://trello.com/c/3KeAZPC3/79-1-5
> sunrise-fixbug-trigonometry_1.5

- exercises/trigonometry_2.html
https://trello.com/c/bbGJz1I1/80-2
> sunrise-fixbug-trigonometry_2

- exercises/exponents_1.html
https://trello.com/c/2u62LN0k/86-1
> sunrise-fixbug-exponents_1

- exercises/solid_geometry.html
https://trello.com/c/dzx6NauG/92-int-tripri-v
> sunrise-fixbug-solid_geometry

- exercises/unit_circle.html
https://trello.com/c/P2HorczK/81--
> sunrise-fixbug-unit_circle

- exercises/area_unit_cm_square.html
https://trello.com/c/xJanbDWv/63--
> sunrise-fixbug-area_unit_cm_square

- exercises/application_of_scientific_notation_2.html
https://trello.com/c/8vgph9MK/108-case3
> sunrise-fixbug-application_of_scientific_notation_2

- exercises/writing_and_interpreting_decimals.html
https://trello.com/c/DU3EkgkJ/99-case2
> sunrise-fixbug-writing_and_interpreting_decimals

- exercises/quadratics_word_problems.html
https://trello.com/c/MqKfy6PD/101-case2
> sunrise-fixbug-quadratics_word_problems

- exercises/axis_of_symmetry.html
https://trello.com/c/OmEUqowh/103--
> sunrise-fixbug-axis_of_symmetry

- exercises/multiplying_and_dividing_negative_numbers.html
https://trello.com/c/ay0oSa3e/100-dividing
> Sunrise fixbug multiplying and dividing negative numbers

- exercises/telling_time_0.5.html
https://trello.com/c/CoF7ASVm/104-analog
> sunrise-fixbug-telling_time_0.5

- exercises/understand_large_numbers_and_conversion.html
https://trello.com/c/ML9707hA/107--
> sunrise-fixbug-understand_large_numbers_and_conversion

- exercises/area_of_a_circle.html
https://trello.com/c/QMpf0Vsj/112-circle-c-to-k
> sunrise-fixbug-area_of_a_circle

- exercises/variance.html
https://trello.com/c/kgqJWQnA/111-sample
> sunrise-fixbug-variance

- khan-exercise.js
> 功能更完整的全型轉半型

- exercises/understand_range_of_graphie.html
修改interactive.js中addMovableCircle中圓變大，修改此題答案驗證範圍
> sunrise-ficbug-understand_range_of_graphie-issue

- exercises/notation_calculation_type.html
https://trello.com/c/EWzsSWtk/48-case1
> sunrise-fixbug-notation_calculation_type

- exercises/adding_and_subtracting_decimals_word_problems.html
https://trello.com/c/z8WtwAqL/113--
> sunrise-fixbug-adding_and_subtracting_decimals_word_problems

- exercises/ineq_solutions.html
20150624 均一習題 html 規格書：不等式的解 ineq_solutions
> sunrise commit ineq solutions

- exercises/place_value_big_number.html
- utils/math-format.js
https://trello.com/c/DcKMB2yU/97-3-caseb1
> sunrise-fixbug-place_value_big_number

- exercises/cube_volume_calculation.html
https://trello.com/c/zBDps3NN/116-case1
> sunrise-fixbug-cube_volume_calculation

- exercises/radius_diameter_and_circumference_314_1.html
https://trello.com/c/vFJZM8ST/114-circle-c-to-r
> sunrise-fixbug-radius_diameter_and_circumference_314_1

- exercises/m2nds-af.html
20150727 m2nds-af 10000內的錢 (無 5 系列)
> sunrise-commit-m2nds-af-n

- exercises/m2nds-ae.html
20150727 m2nds-ae 10000內的錢 (含 5 系列)
> sunrise-commit-m2nds-ae-n

- exercises/m2nds-ac.html
> sunrise-commit-m2nds-ac-n

- exercises/arc_length_and_radius.html
> sunrise-commit-arc_length_and_radius-n

- exercises/ineq_compare_2.html
20150630 均一習題 html 規格書：進階比大小 ineq_compare_2
> sunrise-commit-ineq_compare_2

- exercises/ineq_symbol_meaning.html
20150630 均一習題 html 規格書：不等式符號的意義 ineq_symbol_meaning
> sunrise-commit-ineq_symbol_meaning

- exercises/triangle_side_ratio_cot_sec_csc.html
20150722 均一習題 html 規格書：三角邊長比(cot,sec,csc)
> sunrise-commit-triangle_side_ratio_cot_sec_csc

- exercises/m1ajj-aa.html
> sunrise-commit-m1ajj-aa

- exercises/m1ajj-gb.html
> sunrise-commit-m1ajj-gb

- exercises/m1ajj-ga.html
> sunrise-commit-m1ajj-ga

- exercises/m1stx-aa.html
> sunrise-commit-m1stx-aa

- exercises/m1ajj-ie.html
> sunrise-commit-m1ajj-ie

- exercises/m1ajj-id.html
> sunrise-commit-m1ajj-id

- exercises/m1ajj-ic.html
> sunrise-commit-m1ajj-ic

- exercises/m1ajj-ia.html
> sunrise-commit-m1ajj-ia

- exercises/m1ajj-ib.html
> sunrise-commit-m1ajj-ib

- exercises/m1ajj-ha.html
20150814 m1ajj-ha 三位數加一位數的直式加法
> sunrise-commit-m1ajj-ha

- exercises/m1ajj-hb.html
20150814 m1ajj-hb 三位數加二位數的直式加法
> sunrise-commit-m1ajj-hb

- exercises/m1ajj-he.html
20150814 m1ajj-he三位數減一位數的直式減法(需借位)
> sunrise-commit-m1ajj-he

- exercises/m1ajj-hf.html
20150814 m1ajj-hf 三位數減二位數的直式減法(一次借位)
> sunrise-commit-m1ajj-hf

- exercises/m1ajj-hg.html
20150814 m1ajj-hg 三位數減三位數的直式減法(一次借位)
> sunrise-commit-m1ajj-hg

- exercises/m1ajj-hh.html
> sunrise-commit-m1ajj-hh

- exercises/m1stx-ea.html
> sunrise-commit-m1stx-ea

- exercises/m1stx-ec.html
20150810 m1stx-ec正三角形與正方形的邊長關係
> sunrise-commit-m1stx-ec

- exercises/m3sdb-di.html
> sunrise-commit-m3sdb-di

- exercises/m3sdb-ba.html
> sunrise-commit-m3sdb-ba

- exercises/m3sdb-bc.html
> sunrise-commit-m3sdb-bc

- exercises/m3sdb-bd.html
> sunrise-commit-m3sdb-bd

- exercises/m2afs-af.html
> sunrise-commit-m2afs-af

- exercises/m2sjy-ac.html
> sunrise-commit-m2sjy-ac

- exercises/m2afs-ah.html
> sunrise-commit-m2afs-ah

- exercises/m2ndl-aa.html
> sunrise-commit-m2ndl-aa

- exercises/m2ndl-ab.html
> sunrise-commit-m2ndl-ab

- exercises/m3ayj-ba.html
> sunrise-commit-m3ayj-ba

- exercises/m3ayb-db.html
> sunrise-commit-m3ayb-db

- exercises/m3ayb-dd.html
20150814 m3ayb-dd 用短除法找最小公倍數 (1)
> sunrise-commit-m3ayb-dd

- exercises/m3ayj-cd.html
> sunrise-commit-m3ayj-cd

- exercises/m3sdb-dc.html
20150814 m3sdb-dc 平行四邊形的「底」與「高」
> sunrise-commit-m3sdb-dc

- exercises/adding_and_subtracting_decimals_word_problems.html
- exercises/adding_subtracting_no_carry_3.html
- exercises/addition_of_vary_denominator_fraction.html
- exercises/age_word_problems.html
- exercises/arithmetic_sequences_3.html
- exercises/discount_tax_and_tip_word_problems.html
- exercises/dividing_fractions_word_problems.html
- exercises/division_word_problems_2.html
- exercises/estimation_three-digit_add_sub.html
- exercises/fraction_of_one_step_to_unknow_formula.html
- exercises/interpreting_negative_numbers.html
- exercises/kg_g_time_div.html
- exercises/l_ml_time_div.html
- exercises/least_common_multiple_and_greatest_common_divisor_word_problems.html
- exercises/markup_and_commission_word_problems.html
- exercises/multiplication_and_division_order.html
- exercises/multiplication_word_problems.html
- exercises/negative_number_word_problems.html
- exercises/percentage_word_problems_1.html
- exercises/radical_multiplication_and_division.html
- exercises/ratio.html
- exercises/recognize_num_less_than_10000.html
- exercises/seq-arithmetic-sequences-l1.html
- exercises/seq-arithmetic-sequences-l2.html
- exercises/seq_arithmetic_series_1.html
- exercises/seq_arithmetic_series_2.html
- exercises/seq_arithmetic_series_using_mean_value.html
- exercises/sequences_word_problems.html
- exercises/subtract_of_positive_negative_fraction.html
- exercises/subtraction_of_vary_denominator_fraction.html
> sunrise-fixbug-spin-problems

- exercises/m3sdb-bb.html
> sunrise-commit-m3sdb-bb

- exercises/m2nds-af.html
- exercises/symmetrical_line_graphics.html
fix bugs for 2 exercises (symmetrical_line_graphics/scrach pad covering money images)
> Fixingbugs

- exercises/exploring_mean_and_median.html
- utils/mean-and-median.js
> sunrise-fixbug-exploring_mean_and_median

- exercises/m4sxs-dd.html
> sunrise-commit-m4sxs-dd

- exercises/m4sxs-dc.html
> sunrise-commit-m4sxs-dc

- exercises/triangle_types.html
https://trello.com/c/y9S27Bx7/123-knownangles
> sunrise-fixbug-triangle_types

- exercises/volume_unit_conversion.html
https://trello.com/c/251clUQc/117-anumber-to-bnumber
> sunrise-fixbug-volume_unit_conversion

- exercises/short_divide_gcf_and_lcm.html
https://trello.com/c/bpXLH895/118-case2
> sunrise-fixbug-short_divide_gcf_and_lcm

- exercises/m1ajj-hi.html
> sunrise-commit-m1ajj-hi-n

- exercises/m1acf-ba.html
> sunrise-commit-m1acf-ba

- exercises/m1acf-bb.html
> sunrise-commit-m1acf-bb

- exercises/m1acf-bc.html
> sunrise-commit-m1acf-bc

- exercises/m1acf-bd.html
> sunrise-commit-m1acf-bd

- exercises/m1acf-ca.html
> sunrise-commit-m1acf-ca

- exercises/m1acf-cb.html
> sunrise-commit-m1acf-cb

- exercises/m1acf-cc.html
> sunrise-commit-m1acf-cc

- exercises/m1acf-cd.html
> sunrise-commit-m1acf-cd

- exercises/m3sdb-dd.html
20150814 m3sdb-dd三角形的高(含直角三角形)
> sunrise-commit-m3sdb-dd

- exercises/m3ayb-ce.html
> sunrise-commit-m3ayb-ce

- exercises/m1acf-ef.html
> sunrise-commit-m1acf-ef

- exercises/m1acf-ee.html
> sunrise-commit-m1acf-ee

- exercises/m1acf-ed.html
> sunrise-commit-m1acf-ed

- exercises/m1acf-ec.html
> sunrise-commit-m1acf-ec

- exercises/m3syj-da.html
20150828 m3syj-da扇形的面積（給半徑、幾分之幾圓）
> sunrise-commit-m3syj-da

- exercises/m3syj-cb.html
> sunrise-commit-m3syj-cb

- exercises/m3slt-fc.html
> sunrise-commit-m3slt-fc

- exercises/m1acf-fc.html
> sunrise-commit-m1acf-fc

- exercises/m3ayj-eb.html
> sunrise-commit-m3ayj-eb

- exercises/parallel_quadrilateral_meaning.html
https://trello.com/c/DGtHeS9n/124--
> sunrise-fixbug-parallel_quadrilateral_meaning

- exercises/m2nds-ac.html
https://trello.com/c/INM6l1OQ/122-case1
> sunrise-fixbug-m2nds-ac

- exercises/m3ayb-dd.html
20150814 m3ayb-dd 用短除法找最小公倍數 1
deploy problem
> deploy-problem-m3ayb-dd-new

- exercises/m2acx-dc.html
20150828 m2acx-dc 三位數除以一位數商為三位數且有餘數
> sunrise-commit-m2acx-dc

- exercises/m2acx-de.html
20150828 m2acx-de 三位數除以一位數商為二位數且整除
> sunrirse-commit-m2acx-de

- exercises/m2acx-dd.html
20150828 m2acx-dd 三位數除以一位數需要補0的情形
> sunrise-commit-m2acx-dd

- exercises/m2acx-ec.html
> sunrise-commit-m2acx-ec

- exercises/m2acx-ed.html
> sunrise-commit-m2acx-ed

- exercises/m2acx-eb.html
> sunrise-commit-m2acx-eb

- exercises/m2acx-ea.html
> sunrise-commit-m2acx-ea

- exercises/m1acf-da.html
> sunrise-commit-m1acf-da

- exercises/m2acx-hj.html
20150828 m2acx-hj 四位數除以一位數商為三位數
> sunrise-commit-m2acx-hj

- exercises/m2acx-hd.html
20150828 m2acx-hd 四位數除以二位數商為三位數
> sunrise-commit-m2acx-hd

- exercises/m2acx-hc.html
> sunrise-commit-m2acx-hc

- exercises/m2acx-hb.html
> sunrise-commit-m2acx-hb

- exercises/m2acx-ha.html
20150828 m2acx-ha 四位數除以一位數商為四位數
> sunrise-commit-m2acx-ha

- exercises/m2acx-gc.html
20150828 m2acx-gc 四位數(有缺位)乘以二位數
> sunrise-commit-m2acx-gc

- exercises/m2acx-gb.html
> sunrise-commit-m2acx-gb

- exercises/m2acx-hk.html
> sunrise-commit-m2acx-hk

- exercises/m2acx-hl.html
20150828 m2acx-hl 三位數除以二位數商為一位數
> sunrise-commit-m2acx-hl

- exercises/m2acx-hm.html
20150828 m2acx-hm 三位數除以二位數商為二位數
> sunrise-commit-m2acx-hm

- exercises/m2acx-hn.html
20150828 m2acx-hn 四位數除以二位數商為三位數(需補0)
> sunrise-commit-m2acx-hn

- exercises/m2acx-ho.html
20150828 m2acx-ho 四位數除以二位數商為二位數
> sunrise-commit-m2acx-ho

- exercises/m3acx-aa.html
> sunrise-commit-m3acx-aa

- exercises/m3acx-ab.html
> sunrise-commit-m3acx-ab

- exercises/m3slt-ca.html
> sunrise-commit-m3slt-ca

- exercises/m3acx-ac.html
> sunrise-commit-m3acx-ac

- exercises/m3acx-af.html
20150828 m3acx-af 二位數乘以三位數(交換順序)
> sunrise-commit-m3acx-af

- exercises/m2afs-cf.html
- utils/graphie-helpers-arithmetic.js
> sunrise-commit-m2afs-cf

- exercises/m2afs-cg.html
- utils/graphie-helpers-arithmetic.js
> sunrise-commit-m2afs-cg

- exercises/m2ajj-ce.html
> sunrise-commit-m2ajj-ce

- exercises/m2acx-ac.html
20150828 m2acx-ac 三位數乘以一位數(有進位)
> sunrise-commit-m2acx-ac

- exercises/m2acx-ba.html
> sunrise-commit-m2acx-ba

- exercises/m2acx-bb.html
> sunrise-commit-m2acx-bb

- exercises/concepts_related_to_parallelogram.html
https://trello.com/c/nqbRKFIE/125--
> sunrise-fixbug-concepts_related_to_parallelogram

- exercises/area_of_triangles_1.html
https://trello.com/c/B0OTPu83/126-1-acute-triangle
> sunrise-fixbug-area_of_triangles_1

- exercises/m2acx-ib.html
> sunrise-commit-m2acx-ib

- exercises/m2acx-ia.html
> sunrise-commit-m2acx-ia

- exercises/m2acx-ic.html
> sunrise-commit-m2acx-ic

- exercises/m3slt-cb.html
> sunrise-commit-m3slt-cb

- exercises/m2acx-fb.html
> sunrise-commit-m2acx-fb

- exercises/m2acx-fc.html
> sunrise-commit-m2acx-fc

- exercises/m2acx-fd.html
> sunrise-commit-m2acx-fd

- exercises/m2acx-fe.html
> sunrise-commit-m2acx-fe

- exercises/m2jslt-ac.html
> sunrise-commit-m2jslt-ac

- exercises/m2acx-id.html
> sunrise-commit-m2acx-id

- exercises/m2afs-ba.html
> sunrise-commit-m2afs-ba

- exercises/m3slt-fa.html
> sunrise-commit-m3slt-fa

- exercises/m2afs-cd.html
> sunrise-commit-m2afs-cd

- exercises/m2jslt-aa.html
> sunrise-commit-m2jslt-aa

- exercises/m2jslt-ab.html
> sunrise-commit-m2jslt-ab

- exercises/m1ajj-fb.html
- utils/graphie-helpers-arithmetic.js
> sunrise-commit-m1ajj-fb

- exercises/multiplication_association_word_problems.html
https://trello.com/c/ZsOX6c22/128--
> sunrise-fixbug-multiplication_association_word_problems

- exercises/area_unit_cm_square.html
https://trello.com/c/yqyyHqoi/127-case3
> Sunrise fixbug area unit cm square n2

- utils/answer-types.js
> set display:none as default value for #fraction_mode_div

- utils/answer-types.js
處理使用 .parent() 時，沒有 parent 的 case
> fix no parent bug

- exercises/m2afs-bf.html
> sunrise-commit-m2afs-bf

- exercises/converting_decimals_to_fractions_1.html
https://trello.com/c/5rEJ8RQP/136-1-to-the-hundredth
> sunrise-fixbug-converting_decimals_to_fractions_1

- exercises/ratio_and_the_ratio_of.html
https://trello.com/c/VWLn6Cpm/132-2-case7
> sunrise-fixbug-ratio_and_the_ratio_of

- exercises/halves_and_fourths.html
https://trello.com/c/lx7cNKTe/130--
> sunrise-fixbug-halves_and_fourths

- exercises/meaning_congruent_planar_graph.html
https://trello.com/c/jWnFzXkQ/141--
> sunrise-fixbug-meaning_congruent_planar_graph

- exercises/m2ajj-cc.html
> sunrise-commit-m2ajj-cc

- exercises/m2acx-ce.html
> sunrise-commit-m2acx-ce

- exercises/m2afs-ed.html
20150828 m2afs-ed 假分數與帶分數的等值分數
> sunrise-commit-m2afs-ed

- exercises/m2afs-df.html
20150828 m2afs-df 分數與除法的關係
在IE 8測試的時候，碰到indexOf的錯誤，看了代碼，報錯在answer-types.js中196行，var supportedFractionTypes = fractionForms.filter(function(n) {
return acceptableForms.indexOf(n) != -1
})
我們暫時不在IE里繼續測試啦
這幾天ipad不在身邊，沒法測試，下禮拜我們再帶過來測試下，就先pr上去了
> sunrise-commit-m2afs-df

- exercises/m3sdb-df.html
> sunrise-commit-m3sdb-df

- exercises/adding_subtracting_dicimals_fractions_and_percentage.html
- exercises/multiplication_formula_sub.html
- exercises/volume_unit_conversion.html
* 有些人的題目空白，原因是在 math.js 內的 toFraction 跑太久跑不出來。跑不出來的原因是餵入的參數小數點後有太多位數。會有小數點後太多位數的情況，則可能肇因於：
1. data-ensure 的 scope 沒有保護好變數的範圍
2. 在 data-ensure 內的判斷式，誤用了 T[0].toString().length < 10 之類的方式來判斷位數，但是沒有考慮到 javascript 有 1.23e-8 這種表達法
> Fix cheng principal white exercise

- exercises/dividing_decimals.html
https://trello.com/c/6mmL8Vkz/138--
> sunrise-fixbug-dividing_decimals

- exercises/recognizing_factoring.html
https://trello.com/c/QDcLvD27/129--
> sunrise-fixbug-recognizing_factoring

- utils/answer-types.js
how to test: 
看看 derivative_intuition 這一個習題是否正確回答可以到下一題
> check isSolutionAreaInTable variable before entering fraction mode

- exercises/m3syj-cc.html
20150828 m3syj-cc 縮放對圓面積與周長的影響
> sunrise-commit-m3syj-cc

- exercises/m2afs-af.html
https://trello.com/c/Ipt8kzav/143-m2afs-af-html-case2
> sunrise-fixbug-m2afs-af

- exercises/basic_concept_of_circumcenter.html
https://trello.com/c/a6Ghnwnh/151-basic-concept-of-circumcenter-case3
> sunrise-fixbug-basic_concept_of_circumcenter

- exercises/m3acx-ad.html
> sunrise-commit-m3acx-ad

- exercises/trapezoid_nature.html
> sunrise-commit-trapezoid_nature

- exercises/m3slt-cd.html
20150828 m3slt-cd   簡單複合形體的表面積
> sunrise-commit-m3slt-cd

- exercises/m3sdb-eg.html
20150828 m3sdb-eg複合圖形的面積計算(進階)
> sunrise-commit-m3sdb-eg

- exercises/m3abs-cb.html
> sunrise-commit-m3abs-cb

- exercises/m2acx-fa.html
> sunrise-commit-m2acx-fa

- exercises/m2sjy-ac.html
https://trello.com/c/Qv1MYsdw/159-m2sjy-ac-case3
> Bugfix set snapX,snapY to 0

- exercises/prime_factorization.html
https://trello.com/c/6ppQ7Fiq/154--
刪除了 prime 的case
> delete prime case

- exercises/recognize_graph_zoom_effect.html
https://trello.com/c/GuNYuujJ/140--
> sunrise-fixbug-recognize_graph_zoom_effect

- exercises/draw_a_pie_chart.html
case1 & case3 delete "%"
https://trello.com/c/Jscpg9Ui/158-draw-a-pie-chart-case1
> sunrise-fixbug-draw_a_pie_chart

- exercises/m2acx-ee.html
https://github.com/junyiacademy/junyiexercise/pull/450
> sunrise-fixbug-m2acx-ee

- exercises/m2sjy-aa.html
https://trello.com/c/y3zeMdmY/148-m2sjy-aa
> sunrise-fixbug-m2sjy-aa 點選區域

- exercises/dividing_decimals.html
https://trello.com/c/6mmL8Vkz/138--
bug 確認
> sunrise-fixbug-dividing_decimals-nn

- exercises/meaning_congruent_planar_graph.html
https://trello.com/c/jWnFzXkQ/141--
取消 radio 焦點
> sunrise-fixbug-meaning_congruent_planar_graph-n

- exercises/reading_stem_and_leaf_plots.html
https://trello.com/c/5le66EQ2/145--
修改超版問題
> sunrise-fixbug-reading_stem_and_leaf_plots

- exercises/count_one_by_one_1.html
> sunrise-fixbug-count_one_by_one_1

- exercises/m3sdb-ee.html
> sunrise-commit-m3sdb-ee

- khan-exercise.js
由於 understanding_square_rectangular.html?debug&problem=case1 的答案欄位是 set
有五個答案框，因此 guess 這個值會是一個 [Array[5]]
所以在全形轉半形的function中，不會處理到 array 的 case
目前處理方式是在丟入asc這個function前，先判斷 guess 下是否是個array
如果是就批次丟入
> add an if to check whether there is a sub array

- utils/word-problems.js
on trello 問題編號：20160420132629642，使用者回覆建議「茄子並非水果」，在word-problems.js檔中將茄子拿掉。
> edit 1 item in fruit

- css/khan-site.css
> remove prefix host in url

- utils/graphie-helpers-arithmetic.js
把進位的位值對齊實際上加法時的位值，另外將最後的加法符號去掉。
> modify the multiplier to the taiwan version

- css/combined.css
- css/khan-exercise.css
- interface.js
modify interface.js 
shake raising_hand btn
> Raising hand strugle

- interface.js
- khan-exercise.js
SVG click to send GA code once,then remove GA_code
When new problem render, add GA_code in SVG again.
> scratchpad add GA

- utils/graphie-helpers-arithmetic.js
修改長除法
使其在不夠除時能在同一行算式處理，而不是每一位每一位處理。
修改減法
使其在把首位的0去掉的時候可以出現提示"0可以省略"
將借位改為現行用語退位。
> Bugfix arithmetic helpers

- utils/math-format.js
- utils/word-problems.js
將數字轉成國字
例如 40000900 翻譯成四千萬零九百
原本沒有那個零，已將零補上
然後將一些怪異運動項目刪除
> 修改零會沒有出現的bug

- interface.js
新增play()「答對」和「答錯」音效的code到 khan-exercises/interface.js
> add right and wrong answers sound effects

- interface.js
> 問題:部分題目的答案按鈕無反應或功能不正常

- interface.js
> New vibrate

- interface.js
> add audio ab test

- interface.js
> remove the ab test

- utils/tex.js
Method name changed after upgrading KaTex.
Ref: https://github.com/junyiacademy/perseus/pull/32
> change katex.process to katex.render
